Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,10 +25,19 @@ jobs:
           Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
           Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
 
-      - name: Set runneradmin password
-        run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "${{ secrets.RUNNERADMIN_PASSWORD }}" -Force)
+      - name: Check runneradmin secret
+        run: |
+          if (-not $env:RUNNER_ADMIN -or $env:RUNNER_ADMIN -eq "") {
+            Write-Error "RUNNER_ADMIN secret is missing or empty."
+            exit 1
+          }
         env:
-          RUNNERADMIN_PASSWORD: ${{ secrets.RUNNERADMIN_PASSWORD }}
+          RUNNER_ADMIN: ${{ secrets.RUNNER_ADMIN }}
+
+      - name: Set runneradmin password
+        run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "${{ secrets.RUNNER_ADMIN }}" -Force)
+        env:
+          RUNNER_ADMIN: ${{ secrets.RUNNER_ADMIN }}
 
       - name: Create Tunnel
         run: .\ngrok\ngrok.exe tcp 3389
